[project]
name = "service-auth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.123.3",
    "jwt>=1.4.0",
    "passlib>=1.7.4",
    "pydantic-settings>=2.12.0",
    "sqlalchemy>=2.0.44",
]
