services:

  # Service d'authentication
  service_auth:
    build:
      context: ./backend/app/api/service_auth_api
      dockerfile: Dockerfile
    image: service_auth
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${PORT}", "${DEBUG:+--reload}"]
    env_file:
      - .env.dev
    ports:
      - "${PORT_1}:${PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SERVICE_NAME=${SERVICE_NAME_1}
    healthcheck:
      test: ["CMD", "curl", "-f", "${HEALTH_CHECK_ENDPOINT}"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 90s
    networks:
      - app-network
    depends_on:
      - db

  # Service de traçabilité de baggage
  service_baggages:
    build:
      context: ./backend/app/api/service_baggages_api
      dockerfile: Dockerfile
    image: service_baggages
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${PORT}", "${DEBUG:+--reload}"]
    env_file:
      - .env.dev
    ports:
      - "${PORT_2}:${PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SERVICE_NAME=${SERVICE_NAME_2}
    healthcheck:
      test: ["CMD", "curl", "-f", "${HEALTH_CHECK_ENDPOINT}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s
    networks:
      - app-network
    depends_on:
      - db
  
   # Service de météo IA
  service_meteo_ia:
    build:
      context: ./backend/app/api/service_meteo_ia_api
      dockerfile: Dockerfile
    image: service_meteo_ia
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${PORT}", "${DEBUG:+--reload}"]
    env_file:
      - .env.dev
    ports:
      - "${PORT_3}:${PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SERVICE_NAME=${SERVICE_NAME_3}
    healthcheck:
      test: ["CMD", "curl", "-f", "${HEALTH_CHECK_ENDPOINT}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s
    networks:
      - app-network
    depends_on:
      - db
  
  # frontend:
  #     build:
  #       context: ./frontend
  #       dockerfile: Dockerfile
  #     image: aerocast-frontend
  #     env-file:
  #     - .env.dev
  #     ports:
  #       - "{PORT_F1}:{PORT_F2}"
  #     depends_on:
  #       service_auth:
  #         condition: service_healthy 
  #       service_baggages:
  #         condition: service_healthy
  #       service_meteo_ia:
  #         condition: service_healthy 
  #       networks:
  #         - app-network

    # Service de passerelle des APIs: Nginx
  gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      service_auth:
        condition: service_healthy 
      service_baggages:
        condition: service_healthy
      service_meteo_ia:
        condition: service_healthy
    networks:
      - app-network
  
  # service rabbitmq pour les files de messages
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    
  db:
    image: postgres
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env.dev

volumes:
  db_data:

networks:
  app-network:
      driver: bridge