global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'baggage-service'
    static_configs:
      - targets: ['baggage:8000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth:8000']

  - job_name: 'weather-service'
    static_configs:
      - targets: ['weather:8000']
